_G.autoclicker = true
_G.AutoHatch = true
_G.AutoRebirth = true


while _G.autoclicker == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Events.Tap:FireServer()
wait()
end


while _G.AutoHatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {},
    [2] = "Starter",
    [3] = 1
}

game:GetService("ReplicatedStorage").Events.HatchEgg:InvokeServer(unpack(args))

wait()
end



while _G.AutoRebirth == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 1
}

game:GetService("ReplicatedStorage").Events.Rebirth:FireServer(unpack(args))
wait()
end